// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZaFXjPp5JwUF-Hr7IxAMN8Tg3u2QOF4',
    appId: '1:951552864785:web:75a9c339715574bcdc77b0',
    messagingSenderId: '951552864785',
    projectId: 'ecobazzarhub-74abb',
    authDomain: 'ecobazzarhub-74abb.firebaseapp.com',
    storageBucket: 'ecobazzarhub-74abb.firebasestorage.app',
    measurementId: 'G-L4F2LY0V54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMm58mDGzxF0WQM5OHGWQWa9m6VE2pnQA',
    appId: '1:951552864785:android:0965c7c03ba34ee4dc77b0',
    messagingSenderId: '951552864785',
    projectId: 'ecobazzarhub-74abb',
    storageBucket: 'ecobazzarhub-74abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQNxhAwDBellS1N7PRvc_-k1NcNBhFVM',
    appId: '1:951552864785:ios:cf62f5757913910bdc77b0',
    messagingSenderId: '951552864785',
    projectId: 'ecobazzarhub-74abb',
    storageBucket: 'ecobazzarhub-74abb.firebasestorage.app',
    iosClientId: '951552864785-vh1nkg7677k3kr7o78gvjdgu01d2pb7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoBazzarHub',
  );
}
